Insert into SEG_ROLES (COD_ROL, TIP_ROLES)
VALUES (1, 'Administrador');
select * from SEG_ROLES

Update SEG_ROLES
Set TIP_ROLES = 'USUARIO'
WHERE COD_ROL = '2'

Insert into SEG_PERMISOS (COD_PERMISOS, PER_INSERCION,PER_ELIMINAR,PER_ACTUALIZAR,PER_CONSULTAR,FEC_MODIFICACION,COD_ROL)
VALUES (3, '1','1','1','1',current_timestamp,'1');
select * from SEG_PERMISOS